# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

stageName: ${serviceVariable.stageName}
primaryName: ${serviceVariable.primaryName}


replicaCount: 1

image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ${serviceVariable.name}

service:
  type: LoadBalancer
  port: 8080

ingress:
  enabled: false
  annotations: 
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []


  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []


env:
  config:
    NOTASECRET: "123"
    ANOTHER: "another"

affinity: {}
